NAME	= out/lvgl
BASE	= ../../
DIRS	= . $(BASE)drv $(BASE)lib/lvgl \
	$(BASE)lib/lvgl/lv_examples \
	$(BASE)lib/lvgl/lv_examples/src/assets \
	$(BASE)lib/lvgl/lv_examples/src/lv_demo_stress \
	$(BASE)lib/lvgl/lv_examples/src/lv_demo_widgets \
	$(BASE)lib/lvgl/lv_examples/src/lv_demo_benchmark
LVGL_DIR = $(BASE)/lib
LVGL_DIR_NAME = lvgl
include $(BASE)lib/lvgl/lvgl.mk
include $(BASE)common.mk
