NAME	= out/lvgl
BASE	= ../../../
DIRS	= . $(BASE)drv $(BASE)lib/lvgl7 \
	$(BASE)lib/lvgl7/lv_examples \
	$(BASE)lib/lvgl7/lv_examples/src/assets \
	$(BASE)lib/lvgl7/lv_examples/src/lv_demo_stress \
	$(BASE)lib/lvgl7/lv_examples/src/lv_demo_widgets \
	$(BASE)lib/lvgl7/lv_examples/src/lv_demo_benchmark
LVGL_DIR = $(BASE)/lib
LVGL_DIR_NAME = lvgl7
include $(BASE)lib/lvgl7/lvgl.mk
include $(BASE)common.mk
